/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.pharmacyManager;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.User;
import modelDAO.UserService;
import modelPharmacyEnterprise.Prescription;
import modelPharmacyEnterprise.PrescriptionAssignment;
import modelPharmacyEnterpriseDAO.PrescriptionDAO;
import modelPharmacyEnterpriseService.PrescriptionService;
import ui.LoginScreen;
import modelPharmacyEnterprise.Medicine;
import modelPharmacyEnterpriseService.MedicineService;
import ui.DatabaseUtil;


/**
 *
 * @author keerthichandrakanth
 */
public class pharmacyManagerWorkarea extends javax.swing.JPanel {
   private final User pharmacyManager;  
   PrescriptionDAO prescriptionDAO = new PrescriptionDAO();
   PrescriptionService prescriptionService = new PrescriptionService(prescriptionDAO);
   private List<PrescriptionAssignment> prescriptionAssignments;
   private List<Prescription> prescriptions;
   List<Medicine> medicines ;
  
    /**
     * Creates new form pharmacyManagerWorkarea
     */
     public pharmacyManagerWorkarea(User pharmacyManager) {
        this.pharmacyManager = pharmacyManager;
        initComponents();
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menubar = new javax.swing.JPanel();
        btnViewDetails = new javax.swing.JButton();
        btnMedicineOrder = new javax.swing.JButton();
        btnPrescription = new javax.swing.JButton();
        btnMedicinePrescription = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setBackground(new java.awt.Color(247, 249, 252));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menubar.setBackground(new java.awt.Color(247, 249, 252));

        btnViewDetails.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnMedicineOrder.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnMedicineOrder.setText("Medicine Order");
        btnMedicineOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicineOrderActionPerformed(evt);
            }
        });

        btnPrescription.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnPrescription.setText("Prescription");
        btnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescriptionActionPerformed(evt);
            }
        });

        btnMedicinePrescription.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnMedicinePrescription.setText("Medicine Details");
        btnMedicinePrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicinePrescriptionActionPerformed(evt);
            }
        });

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menubarLayout = new javax.swing.GroupLayout(menubar);
        menubar.setLayout(menubarLayout);
        menubarLayout.setHorizontalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(menubarLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menubarLayout.createSequentialGroup()
                        .addComponent(btnPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnMedicinePrescription)
                        .addGap(18, 18, 18)
                        .addComponent(btnMedicineOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menubarLayout.createSequentialGroup()
                        .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        menubarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMedicineOrder, btnMedicinePrescription});

        menubarLayout.setVerticalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnViewDetails))
                .addGap(18, 18, 18)
                .addGroup(menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMedicineOrder)
                    .addComponent(btnPrescription)
                    .addComponent(btnMedicinePrescription))
                .addGap(18, 18, 18))
        );

        jSplitPane1.setLeftComponent(menubar);

        workArea.setBackground(new java.awt.Color(247, 249, 252));
        workArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
         viewDetails vd = new viewDetails(workArea, pharmacyManager);
         workArea.add("LoginScreen", vd);
         CardLayout layout = (CardLayout) workArea.getLayout();
         layout.next(workArea);
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescriptionActionPerformed
       try {
           // TODO add your handling code here:
           PrescriptionDAO prescriptionDAO = new PrescriptionDAO();
           PrescriptionService prescriptionService = new PrescriptionService(prescriptionDAO);
           List<Prescription> prescriptions = prescriptionService.getPrescriptionsForPharmacyManager(pharmacyManager.getId());
           prescription p = new prescription(workArea,prescriptions);
           workArea.add("LoginScreen", p);
           CardLayout layout = (CardLayout) workArea.getLayout();
           layout.next(workArea);
       } catch (SQLException ex) {
           Logger.getLogger(pharmacyManagerWorkarea.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnPrescriptionActionPerformed

    private void btnMedicinePrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicinePrescriptionActionPerformed
        // TODO add your handling code here:
         
         MedicineService medicineService = new MedicineService();
         List<Medicine> medicines = medicineService.getAllMedicines();
         medicineDetails md = new medicineDetails(workArea,medicines);
         workArea.add("Medicine Details", md);
         CardLayout layout = (CardLayout) workArea.getLayout();
         layout.next(workArea);
    }//GEN-LAST:event_btnMedicinePrescriptionActionPerformed

    private void btnMedicineOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicineOrderActionPerformed
        // TODO add your handling code here:
         medicineOrder mo = new medicineOrder(workArea, pharmacyManager);
         workArea.add("Medicine Order", mo);
         CardLayout layout = (CardLayout) workArea.getLayout();
         layout.next(workArea);
        
    }//GEN-LAST:event_btnMedicineOrderActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            DatabaseUtil.closeConnection();
            JOptionPane.showMessageDialog(this, "Logged out successfully!");

            JPanel mainPanel = (JPanel) this.getParent();
            CardLayout layout = (CardLayout) mainPanel.getLayout();
            mainPanel.add(new LoginScreen(mainPanel), "LoginScreen");
            layout.show(mainPanel, "LoginScreen");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error while logging out: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMedicineOrder;
    private javax.swing.JButton btnMedicinePrescription;
    private javax.swing.JButton btnPrescription;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton jButton2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menubar;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
