/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Patient;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelBillingEnterpriseDAO.PrescriptionBillingDAO;
import modelBillingEnterpriseService.PrescriptionBillingService;
import modelPharmacyEnterpriseDAO.PrescriptionDAO;
import modelPharmacyEnterpriseService.PrescriptionService;

/**
 *
 * @author keerthichandrakanth
 */
public class medicineBilling extends javax.swing.JPanel {
        JPanel mainWorkArea;
        int currentUser;
    /**
     * Creates new form medicineBilling
     */
    public medicineBilling(JPanel mainWorkArea,int  patientId) {
        
        this.mainWorkArea = mainWorkArea;
        this.currentUser=patientId;
        initComponents();
        populateTblBilllingDetailsDisplay("All");
    }
    
    
      private void populateTblBilllingDetailsDisplay(String filterStatus) {
    // Define the column names
    String[] columnNames = {
        "Prescription ID", 
        "Medicine Name", 
        "Medicine Price", 
        "Medicine Quantity", 
        "Total Per Medicine", 
        "Total Prescription Amount",
        "Payment Status"    
    };

    // Retrieve the table model from the JTable
    DefaultTableModel model = (DefaultTableModel) tblBilllingDetailsDisplay.getModel();

    // Set the column names to the table model
    model.setColumnIdentifiers(columnNames);

    // Clear existing rows
    model.setRowCount(0);

    // Initialize DAO and Service
    PrescriptionBillingDAO billingDAO = new PrescriptionBillingDAO();
    PrescriptionBillingService billingService = new PrescriptionBillingService(billingDAO);

    try {
        // Fetch data from the Service layer (or directly from DAO)
        List<Object[]> billingSummary = billingService.getBillingSummaryByUserId(currentUser);

        // Filter billing records based on the selected payment status
        List<Object[]> filteredBillingSummary = new ArrayList<>();

        // If "All" is selected, show all rows; otherwise filter by status
        for (Object[] row : billingSummary) {
            String paymentStatus = (String) row[6];  // Assuming Payment Status is the 7th element (index 6)

            // Filter by payment status or show all if "All" is selected
            if ("All".equals(filterStatus) || filterStatus.equals(paymentStatus)) {
                filteredBillingSummary.add(row);
            }
        }

        // Add the filtered rows to the table model
        for (Object[] row : filteredBillingSummary) {
            model.addRow(row);  // Add each row (Object[]) to the table
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error fetching data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
    
   
}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBilllingDetailsDisplay = new javax.swing.JTable();
        cmbBoxFilterBasedonPaymentStatus = new javax.swing.JComboBox<>();
        btnMakePayment = new javax.swing.JButton();

        tblBilllingDetailsDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBilllingDetailsDisplay);

        cmbBoxFilterBasedonPaymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Payment Pending", "Paid" }));
        cmbBoxFilterBasedonPaymentStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxFilterBasedonPaymentStatusActionPerformed(evt);
            }
        });

        btnMakePayment.setText("Make Payment");
        btnMakePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakePaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmbBoxFilterBasedonPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMakePayment)
                        .addGap(487, 487, 487))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(cmbBoxFilterBasedonPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnMakePayment)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBoxFilterBasedonPaymentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxFilterBasedonPaymentStatusActionPerformed
        // TODO add your handling code here:
        String selectedStatus = (String) cmbBoxFilterBasedonPaymentStatus.getSelectedItem();
        populateTblBilllingDetailsDisplay(selectedStatus);
    }//GEN-LAST:event_cmbBoxFilterBasedonPaymentStatusActionPerformed

    private void btnMakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePaymentActionPerformed
        // TODO add your handling code here
         int selectedRow = tblBilllingDetailsDisplay.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a row to update.", "No Selection", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get Prescription ID and Payment Status from the selected row
    int prescriptionId = (int) tblBilllingDetailsDisplay.getValueAt(selectedRow, 0); // Assuming ID is in the first column
    String paymentStatus = (String) tblBilllingDetailsDisplay.getValueAt(selectedRow, 6); // Assuming Payment Status is in the 7th column (index 6)

    // Check if the prescription is already marked as "Paid"
    if ("Paid".equalsIgnoreCase(paymentStatus)) {
        JOptionPane.showMessageDialog(null, "This prescription is already marked as Paid.", "Already Paid", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Confirm update
    int confirmation = JOptionPane.showConfirmDialog(
            null, 
            "Are you sure you want to mark this as Paid?", 
            "Confirm Update", 
            JOptionPane.YES_NO_OPTION
    );

    if (confirmation == JOptionPane.YES_OPTION) {
        PrescriptionService prescriptionService = new PrescriptionService(new PrescriptionDAO());
        // Fetch the prescription by ID
        prescriptionService.updatePrescriptionPaymentStatus(prescriptionId, "Paid");
        // Notify the user and refresh the table
        JOptionPane.showMessageDialog(null, "Payment status updated successfully.", "Update Successful", JOptionPane.INFORMATION_MESSAGE);
        populateTblBilllingDetailsDisplay("All"); // Refresh table to reflect updated data
    }
    }//GEN-LAST:event_btnMakePaymentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMakePayment;
    private javax.swing.JComboBox<String> cmbBoxFilterBasedonPaymentStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBilllingDetailsDisplay;
    // End of variables declaration//GEN-END:variables
}
