/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.enterpriseAdmin;

import java.awt.CardLayout;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import modelDAO.UserDAO;
import ui.DatabaseUtil;
import ui.LoginScreen;

/**
 *
 * @author keerthichandrakanth
 */
public class EnterpriseAdminDashboard extends javax.swing.JPanel {

    private UserDAO userDAO;
    private List<Map<String, Object>> allUsers;

    /**
     * Creates new form enterpriseWorkarea
     */
    public EnterpriseAdminDashboard(Connection connection) {
        this.userDAO = new UserDAO(connection);
        initComponents();
        populateUserTable("All");
    }

    private void loadAllUsers() {
        try {
            allUsers = userDAO.getUsersForEnterprise(1); // Exclude System Admin
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading users: " + e.getMessage());
        }
    }

    private void populateUserTable(String roleFilter) {
        loadAllUsers();
        if (allUsers == null) {
            loadAllUsers();
        }

        List<Map<String, Object>> filteredUsers = allUsers;
        if (roleFilter != null && !roleFilter.equals("All")) {
            filteredUsers = allUsers.stream()
                    .filter(user -> user.get("Role").equals(roleFilter))
                    .toList();
        }

        String[] columns = {"ID", "Name", "Role", "Email", "Contact", "Address"};
        Object[][] data = filteredUsers.stream().map(user -> new Object[]{
            user.get("ID"),
            user.get("Name"),
            user.get("Role"),
            user.get("Email"),
            user.get("Contact"),
            user.get("Address")
        }).toArray(Object[][]::new);

        TblPersons.setModel(new DefaultTableModel(data, columns));
    }

    public JTable getTblPersons() {
        return TblPersons;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPersons = new javax.swing.JTable();
        CmbFilRole = new javax.swing.JComboBox<>();
        BtnUpdate = new javax.swing.JButton();
        BtnView = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnLogOut2 = new javax.swing.JButton();

        jTabbedPane1.setBackground(new java.awt.Color(195, 214, 242));

        jPanel2.setBackground(new java.awt.Color(247, 249, 252));

        TblPersons.setBackground(new java.awt.Color(187, 208, 237));
        TblPersons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblPersons);

        CmbFilRole.setBackground(new java.awt.Color(215, 191, 204));
        CmbFilRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Doctor", "Patient", "Lab Manager", "Lab Technician", "Pharmacy Manager", "Pharmasist", "Insurance Manager", "Billing Manager" }));
        CmbFilRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbFilRoleActionPerformed(evt);
            }
        });

        BtnUpdate.setText("Update User");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnView.setText("View Details");
        BtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewActionPerformed(evt);
            }
        });

        BtnDelete.setText("Delete User");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnAdd.setText("Add User");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CmbFilRole, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(444, Short.MAX_VALUE)
                .addComponent(BtnAdd)
                .addGap(18, 18, 18)
                .addComponent(BtnUpdate)
                .addGap(18, 18, 18)
                .addComponent(BtnView)
                .addGap(18, 18, 18)
                .addComponent(BtnDelete)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(CmbFilRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnView)
                    .addComponent(BtnDelete)
                    .addComponent(BtnAdd))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Users", jPanel2);

        jPanel1.setBackground(new java.awt.Color(247, 249, 252));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enterprise Admin");

        BtnLogOut2.setBackground(new java.awt.Color(199, 180, 127));
        BtnLogOut2.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        BtnLogOut2.setText("<- Log Out");
        BtnLogOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogOut2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(BtnLogOut2)
                .addGap(134, 134, 134)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnLogOut2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogOut2ActionPerformed
        try {
            DatabaseUtil.closeConnection();
            JOptionPane.showMessageDialog(this, "Logged out successfully!");

            JPanel mainPanel = (JPanel) this.getParent();
            CardLayout layout = (CardLayout) mainPanel.getLayout();
            mainPanel.add(new LoginScreen(mainPanel), "LoginScreen");
            layout.show(mainPanel, "LoginScreen");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error while logging out: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLogOut2ActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        try {
            AddUserDialog dialog = new AddUserDialog(
                (Frame) SwingUtilities.getWindowAncestor(this),
                true,
                userDAO
            );
            dialog.setVisible(true);
            if (dialog.isSuccess()) {
                populateUserTable("All");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error while adding user: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        int selectedRow = TblPersons.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user to deactivate.");
            return;
        }

        int userId = (int) TblPersons.getValueAt(selectedRow, 0);
        try {
            if (userDAO.deactivateUser(userId)) {
                JOptionPane.showMessageDialog(this, "User deactivated successfully!");
                populateUserTable("All");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to deactivate user.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error deactivating user: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewActionPerformed
        int selectedRow = TblPersons.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user to view details.");
            return;
        }

        int userId = (int) TblPersons.getValueAt(selectedRow, 0);
        String name = (String) TblPersons.getValueAt(selectedRow, 1);
        String roleName = (String) TblPersons.getValueAt(selectedRow, 2);
        String email = (String) TblPersons.getValueAt(selectedRow, 3);
        String contact = (String) TblPersons.getValueAt(selectedRow, 4);
        String address = (String) TblPersons.getValueAt(selectedRow, 5);

        String message = "User ID: " + userId
        + "\nName: " + name
        + "\nRole: " + roleName
        + "\nEmail: " + email
        + "\nContact: " + contact
        + "\nAddress: " + address;

        JOptionPane.showMessageDialog(this, message, "User Details", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnViewActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        int selectedRow = TblPersons.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user to update.");
            return;
        }

        int userId = (int) TblPersons.getValueAt(selectedRow, 0);
        String name = (String) TblPersons.getValueAt(selectedRow, 1);
        String roleName = (String) TblPersons.getValueAt(selectedRow, 2); // Role
        String email = (String) TblPersons.getValueAt(selectedRow, 3);
        String contact = (String) TblPersons.getValueAt(selectedRow, 4);
        String address = (String) TblPersons.getValueAt(selectedRow, 5);

        UpdateUserDialog dialog = new UpdateUserDialog(
            (Frame) SwingUtilities.getWindowAncestor(this),
            true,
            userDAO,
            userId,
            name,
            contact,
            email,
            address,
            roleName
        );
        dialog.setVisible(true);

        if (dialog.isSuccess()) {
            populateUserTable("All");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void CmbFilRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbFilRoleActionPerformed
        String selectedRole = (String) CmbFilRole.getSelectedItem();
        populateUserTable(selectedRole);
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbFilRoleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnLogOut2;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JButton BtnView;
    private javax.swing.JComboBox<String> CmbFilRole;
    private javax.swing.JTable TblPersons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
