/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package ui.enterpriseAdmin;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Logger;
import modelDAO.UserDAO;
import ui.DatabaseUtil;

/**
 *
 * @author AnjanaSruthiR
 */
public class UpdateUserDialog extends java.awt.Dialog {

    private UserDAO userDAO;
    private final int userId;
    private JTextField txtName, txtContact, txtEmail, txtAddress;
    private boolean success;

    private static final Logger LOGGER = Logger.getLogger(UpdateUserDialog.class.getName());

    /**
     * Creates new form UpdateUserDialog
     */
    public UpdateUserDialog(Frame parent, boolean modal, UserDAO userDAO, int userId, String name, String contact, String email, String address, String roleName) {
        super(parent, modal);
        this.userDAO = userDAO;
        this.userId = userId;

        initComponents();
        TxtName.setText(name);
        TxtContact.setText(contact);
        TxtEmail.setText(email);
        TxtAdd.setText(address);

        // Set the combo box to the current role
        CmbRole.setSelectedItem(roleName);

        // Make email field non-editable
        TxtEmail.setEditable(false);
    }

    public boolean isSuccess() {
        return success;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblAddUser = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtAdd = new javax.swing.JTextField();
        TxtName = new javax.swing.JTextField();
        CmbRole = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtContact = new javax.swing.JTextField();
        BtnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BtnCancel = new javax.swing.JButton();
        TxtEmail = new javax.swing.JTextField();

        setBackground(new java.awt.Color(247, 249, 252));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        LblAddUser.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LblAddUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblAddUser.setText("Update User");
        LblAddUser.setToolTipText("");

        jLabel6.setText("Address");
        jLabel6.setToolTipText("");

        jLabel1.setText("Name");
        jLabel1.setToolTipText("");

        CmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Patient", "Lab Manager", "Lab Technician", "Pharmacy Manager", "Pharmasist", "Insurance Manager", "Billing Manager" }));

        jLabel2.setText("Contact");
        jLabel2.setToolTipText("");

        jLabel7.setText("Role");

        BtnUpdate.setBackground(new java.awt.Color(110, 144, 193));
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        jLabel3.setText("Email");
        jLabel3.setToolTipText("");

        BtnCancel.setBackground(new java.awt.Color(110, 144, 193));
        BtnCancel.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        TxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(27, 27, 27)
                            .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(TxtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addComponent(CmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(LblAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(BtnUpdate)
                        .addGap(46, 46, 46)
                        .addComponent(BtnCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LblAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnCancel))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try {
            String name = TxtName.getText().trim();
            String contact = TxtContact.getText().trim();
            String email = TxtEmail.getText().trim();
            String address = TxtAdd.getText().trim();
            String roleName = (String) CmbRole.getSelectedItem();

            if (name.isEmpty() || contact.isEmpty() || address.isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!contact.matches("\\d{10}")) {
                JOptionPane.showMessageDialog(this, "Invalid contact number. It should be 10 digits!", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int roleId = getRoleId(roleName);
            if (roleId == -1) {
                JOptionPane.showMessageDialog(this, "Invalid role selected!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            boolean updated = userDAO.updateUserWithRole(userId, name, contact, email, address, roleId);
            if (updated) {
                JOptionPane.showMessageDialog(this, "User updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                success = true;
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update user.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            LOGGER.severe("Database error: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel?", "Cancel", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void TxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            try {
                Connection connection = DatabaseUtil.getConnection();
                UserDAO userDAO = new UserDAO(connection);
                
                EnterpriseAdminDashboard dashboard = new EnterpriseAdminDashboard(connection);
                JTable userTable = dashboard.getTblPersons();
                
                if (userTable.getRowCount() == 0) {
                    System.out.println("No users found.");
                    return;
                }

                userTable.setRowSelectionInterval(0, 0);
                int selectedRow = userTable.getSelectedRow();
                if (selectedRow == -1) {
                    System.out.println("No user selected.");
                    return;
                }

                int userId = (int) userTable.getValueAt(selectedRow, 0);
                String name = (String) userTable.getValueAt(selectedRow, 1);
                String roleName = (String) userTable.getValueAt(selectedRow, 2);
                String email = (String) userTable.getValueAt(selectedRow, 3);
                String contact = (String) userTable.getValueAt(selectedRow, 4);
                String address = (String) userTable.getValueAt(selectedRow, 5);

                UpdateUserDialog dialog = new UpdateUserDialog(
                    new Frame(),
                    true,
                    userDAO,
                    userId,
                    name,
                    contact,
                    email,
                    address,
                    roleName
                );

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });

                dialog.setVisible(true);

                if (dialog.isSuccess()) {
                    System.out.println("User updated successfully!");
                } else {
                    System.out.println("User update canceled or failed.");
                }

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
            }
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox<String> CmbRole;
    private javax.swing.JLabel LblAddUser;
    private javax.swing.JTextField TxtAdd;
    private javax.swing.JTextField TxtContact;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private int getRoleId(String roleName) {
        switch (roleName) {
            case "Doctor":
                return 3;
            case "Patient":
                return 4;
            case "Lab Manager":
                return 5;
            case "Lab Technician":
                return 6;
            case "Pharmacy Manager":
                return 7;
            case "Pharmasist":
                return 8;
            case "Insurance Manager":
                return 9;
            case "Billing Manager":
                return 10;
            default:
                return -1; 
        }
    }
}
